services:
  db:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
  app:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
    depends_on:
      - db
volumes:
  db_data: